// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CIS655Project.Models
{
    [Table("Business")]
    public partial class Business
    {
        public Business()
        {
            Jobs = new HashSet<Job>();
        }

        [Key]
        public int BusId { get; set; }
        [Required]
        [Column("BName")]
        [StringLength(50)]
        public string Bname { get; set; }
        [StringLength(20)]
        public string Street { get; set; }
        [StringLength(20)]
        public string City { get; set; }
        [StringLength(2, ErrorMessage ="State name should be initials!")]
        public string State { get; set; }
        [StringLength(50)]
        public string Country { get; set; }
        public int? ZipCode { get; set; }
        [Column("BCategory")]
        [StringLength(30)]
        public string Bcategory { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(50)]
        public string Pwd { get; set; }

        [InverseProperty("Bus")]
        public virtual BusinessRole BusinessRole { get; set; }
        [InverseProperty(nameof(Job.Bus))]
        public virtual ICollection<Job> Jobs { get; set; }
    }
}