// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CIS655Project.Models
{
    [Table("JobApplication")]
    public partial class JobApplication
    {
        [Key]
        public int AppId { get; set; }
        public int? UserId { get; set; }
        public int? JobId { get; set; }

        [ForeignKey(nameof(JobId))]
        [InverseProperty("JobApplications")]
        public virtual Job Job { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("JobApplications")]
        public virtual User User { get; set; }
    }
}