// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CIS655Project.Models
{
    public partial class User
    {
        public User()
        {
            JobApplications = new HashSet<JobApplication>();
        }

        [Key]
        public int UserId { get; set; }
        [Required]
        [Column("FName")]
        [StringLength(20)]
        public string Fname { get; set; }
        [Required]
        [Column("LName")]
        [StringLength(20)]
        public string Lname { get; set; }
        [Required]
        [StringLength(20)]
        public string Street { get; set; }
        [Required]
        [StringLength(20)]
        public string City { get; set; }
        [Required]
        [StringLength(2, ErrorMessage ="State name Must be Initials!")]
        public string State { get; set; }
        public int ZipCode { get; set; }
        [Required]
        [StringLength(20)]
        public string EdLevel { get; set; }
        [Required]
        [StringLength(50)]
        public string Email { get; set; }
        [Required]
        [StringLength(20)]
        public string Pwd { get; set; }
        [Required]
        [StringLength(20)]
        public string Country { get; set; }

        [InverseProperty("User")]
        public virtual UserRole UserRole { get; set; }
        [InverseProperty(nameof(JobApplication.User))]
        public virtual ICollection<JobApplication> JobApplications { get; set; }
    }
}